# Generated by Django 2.2.6 on 2021-01-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210123_1527'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
    ]
